### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by RPallas92** [JorgeCastilloPrz/KotlinAndroidArchitecture#15]
Hi, 

really cool project, thanks for sharing. 

How to test HeroesUseCases with i.e. InMemoryDataSource instead of NetworkDataSource?
Right now, HeroesRepository is not receiving the dependency.
Should we include all datasource functions in HeroesContext and user Reader monad?

cc: @JorgeCastilloPrz  @raulraja

**Comment by josete89** [comment]
+1

**Comment by JorgeCastilloPrz** [comment]
Hey! Thanks for your kind words! 🤗  

Any piece of your architecture that you might need to swap at testing time is prone to be on the Reader contexts. The Reader contexts are mimicking the Dagger scoped dependency graphs here, so think about them as all the dependency binding rules that you must override to provide mocks instead of the real ones. On your tests, you could add a new sealed class instance for the context that could override some of the dependencies easily, since those are overridable properties.

I would personally think twice about what you really need to leave out of the graph to achieve isolation in tests. Those are mostly gonna be side effect causing pieces, like the view implementation, api clients, database clients or the threading. For everything not causing effects you can keep your real production code. 

Also keep in mind that testing FP is different than OOP. Since we play with pure functions with no enclosing class most of the time, those are always behaving the same way, and its incredibly easy to use the production code except for some given unpure dependencies like the ones mentioned above.

That said, my testing strategy would be to test the whole app in a black box test scenario just removing the view implementation, threading, and db / api clients. That's why those are provided from inside of the context.

My opinion is to always to move on the black box scenario direction, asserting to final state of a system after exercising a **big** scope of it, mostly to avoid having too weak tests that are too coupled to the implementation. IMHO the less tests you need to write to ensure your system without losing any safety, the better. Tests also mean maintenance, and on FP most of the time you can cover most of your system with just a bunch of them.

But of course, if you really need to test one very isolated piece of your system because you think it's important enough to write a separated test for it, you would need to think on which collaborators from it you need to move to the Reader, since the Reader is the DI strategy here.

I hope this helps you!

For other patterns on how to move on the FP direction over Kotlin, please take a look at the [kategory.io](http://kategory.io) documentation which has a lot of really good and detailed examples and also covers some important patterns.

**Comment by RPallas92** [comment]
Many thanks for your detailed answer, now is much clear to me!
In this case, Does moving NetworkDataSource to Reader make sense? This DataSource is actually doing the API calls.

Maybe I can do as you say, test the whole app without side-effect parts( api client, view, etc)

Thanks you helped me a lot!
